main:
  - name: About
    url: /
    weight: 10
  - name: Event
    identifier: event
    weight: 20
  - name: Upcoming
    parent: event
    url: /event/
    weight: 21
  - name: Past
    parent: event
    url: /event/past/
    weight: 22
  - name: Team
    url: /team/
    weight: 30
  - name: Join us
    url: /contact/
    weight: 40
